language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 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
 local_dir: dist
 on:
   branch: deploy